import test from 'node:test';import assert from 'node:assert/strict';
import {validateFederation,elementKey,relativePlacement} from '../public/bim-viewer/federation-rules.js';
const files=n=>Array.from({length:n},(_,i)=>({id:`file-${i}`,name:`model-${i}.ifc`,url:`/api/models/files/file-${i}`}));
test('federation accepts 20 and rejects 21, zero and duplicate files',()=>{assert.equal(validateFederation(files(20)).length,20);assert.throws(()=>validateFederation(files(21)),/20/);assert.throws(()=>validateFederation([]),/20/);assert.throws(()=>validateFederation([files(1)[0],files(1)[0]]),/inválida/);});
test('ExpressIDs and duplicated GUIDs across files retain source identity',()=>{assert.notEqual(elementKey('architecture',42),elementKey('structure',42));assert.equal(elementKey('architecture',42),'architecture:42');});
test('a shared origin preserves relative placements at large coordinates',()=>{const first=[1,0,0,0,0,1,0,0,0,0,1,0,1000000,2000000,3000000,1],second=[...first];second[12]+=12;second[13]+=3;const a=relativePlacement(first,[1000000,2000000,3000000]),b=relativePlacement(second,[1000000,2000000,3000000]);assert.deepEqual(a.slice(12,15),[0,0,0]);assert.deepEqual(b.slice(12,15),[12,3,0]);assert.equal(first[12],1000000);});
import {resolveLinks} from '../public/bim-viewer/federated-planning.js';
import {generateSequence} from '../public/bim-viewer/sequence.js';
test('federated schedules retain native GUIDs and separate duplicate GUIDs by source',()=>{const e={id:42,globalId:'same-guid',type:'IFCCOLUMN',name:'P1',storeyId:10,storeyName:'Térreo',elevation:0,hasGeometry:true};const inventory={federationId:'fed-1',signature:'fed-1',name:'Conjunto',complete:true,models:[{name:'A',geometry_processed:1,elements_in_model:1},{name:'B',geometry_processed:1,elements_in_model:1}],elements:[{...e,sourceId:'a',sourceName:'a.ifc',key:'a:42'},{...e,sourceId:'b',sourceName:'b.ifc',key:'b:42'}]};const bundle=generateSequence(inventory,{start:'2026-10-07'});assert.equal(bundle.elements.length,2);assert.equal(bundle.sequence.pending.length,0);assert.equal(bundle.federation_id,'fed-1');assert.equal(bundle.sources.ifc_models.length,2);assert.deepEqual(bundle.elements.map(l=>l.guid),['same-guid','same-guid']);assert.notEqual(bundle.elements[0].wbs,bundle.elements[1].wbs);const records=new Map([['a:42',{key:'a:42',fileId:'a',guid:'same-guid'}],['b:42',{key:'b:42',fileId:'b',guid:'same-guid'}]]);assert.equal(resolveLinks(records,bundle.elements).size,2);assert.equal(resolveLinks(records,[{guid:'same-guid',wbs:'legacy'}]).size,0);assert.throws(()=>generateSequence({...inventory,complete:false}),/completo/);});
