import {finishDate} from '../../public/bim-viewer/sequence.js';
export function shortId(row,index){return row.virtual_group?'—':row.outline_number||String(index+1);}
export function displayTree(rows){
 const output=[],parents=new Map();
 if(rows.some(r=>r.summary)){
  const stack=[];
  for(const row of rows){const level=Number.isFinite(row.outline_level)?row.outline_level:row.wbs==='0'?0:row.wbs.split('.').length;while(stack.length&&stack.at(-1).level>=level)stack.pop();parents.set(row.wbs,stack.map(p=>p.wbs));output.push({...row,display_level:stack.length});if(row.summary)stack.push({wbs:row.wbs,level});}
 }else{
  const groups=new Map();for(const row of rows){const name=row.phases?.[0]||'Atividades';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(row);}
  for(const [name,children] of groups){const wbs='@phase:'+name,starts=children.map(r=>r.start).filter(Boolean).sort(),finishes=children.map(r=>r.finish).filter(Boolean).sort();output.push({wbs,name,summary:true,virtual_group:true,display_level:0,start:starts[0]||null,finish:finishes.at(-1)||null,phases:[name],direct_elements:0,planned_percent:null,actual_percent:null});parents.set(wbs,[]);for(const child of children){output.push({...child,display_level:1});parents.set(child.wbs,[wbs]);}}
 }
 return {rows:output,parents};
}
function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new Error('Informe uma data válida.');return value;}
function nextStart(finish,workdays){let d=new Date(finish.slice(0,10)+'T12:00:00Z');do{d.setUTCDate(d.getUTCDate()+1);}while(workdays&&[0,6].includes(d.getUTCDay()));return d.toISOString().slice(0,10);}
function duration(start,finish,workdays){let d=new Date(start+'T12:00:00Z'),end=new Date(finish+'T12:00:00Z'),n=0;while(d<=end){if(!workdays||![0,6].includes(d.getUTCDay()))n++;d.setUTCDate(d.getUTCDate()+1);}return Math.max(1,n);}
function validateGraph(rows){const byId=new Map(rows.map(r=>[r.wbs,r]));for(const row of rows){const seen=new Set([row.wbs]);let p=row.predecessor;while(p){if(seen.has(p))throw new Error('Esse vínculo cria um ciclo de predecessoras.');seen.add(p);const found=byId.get(p);if(!found)throw new Error('Predecessora não encontrada no cronograma.');p=found.predecessor;}}}
function refresh(bundle,rows,links,entry){const active=links.filter(e=>e.active_scope!==false).length,total=bundle.integrity.active_element_count;return {...bundle,user_modified:true,generated_at:new Date().toISOString(),wbs_rows:rows,elements:links,edit_history:[...(bundle.edit_history||[]).slice(-49),{...entry,at:new Date().toISOString()}],sources:{...bundle.sources,schedule:{...bundle.sources.schedule,task_count:rows.length},links:{...bundle.sources.links,row_count:links.length}},integrity:{...bundle.integrity,task_count:rows.length,link_count:links.length,mapped_active_elements:active,matched_active_elements:active,wbs_match_percent:total?active/total*100:0,official_progress_ready:false},progress:{...bundle.progress,official_planned_percent:null,official_actual_percent:null}};}
export function editActivity(bundle,wbs,changes,cascade=false){
 const original=bundle.wbs_rows.find(r=>r.wbs===wbs);if(!original||original.summary)throw new Error('Selecione uma atividade para editar.');const name=String(changes.name||'').trim();if(!name||name.length>300)throw new Error('Informe um nome com até 300 caracteres.');const start=validDate(changes.start),finish=validDate(changes.finish);if(finish<start)throw new Error('O término não pode ser anterior ao início.');
 const workdays=bundle.sequence?.settings?.workdays??true,predecessor=changes.predecessor||'',phase=String(changes.phase||original.phases?.[0]||'Atividades').trim(),phaseChanged=phase!==(original.phases?.[0]||'Atividades');
 let rows=bundle.wbs_rows.map(r=>r.wbs===wbs?{...r,name,start,finish,predecessor,phases:phaseChanged?[phase]:original.phases||[phase],duration_days:duration(start,finish,workdays),evidence:'INFORMADO'}:{...r});validateGraph(rows);
 const pred=rows.find(r=>r.wbs===predecessor);if(pred?.finish&&start<=pred.finish.slice(0,10))throw new Error('A atividade deve começar após o término da predecessora.');
 if(cascade){const queue=[wbs];while(queue.length){const id=queue.shift(),parent=rows.find(r=>r.wbs===id);for(const child of rows.filter(r=>r.predecessor===id)){child.start=nextStart(parent.finish,workdays);child.finish=finishDate(child.start,child.duration_days||1,workdays);child.evidence='INFORMADO';queue.push(child.wbs);}}}else{for(const child of rows.filter(r=>r.predecessor===wbs))if(child.start&&child.start.slice(0,10)<=finish)throw new Error('O término invade uma sucessora. Ative a reprogramação ou ajuste a sucessora primeiro.');}
 const links=bundle.elements.map(e=>e.wbs===wbs?{...e,...(phaseChanged?{phase}:{}),evidence:'INFORMADO'}:e);return refresh(bundle,rows,links,{action:'edit',wbs,previous:{name:original.name,start:original.start,finish:original.finish,predecessor:original.predecessor}});
}
export function addActivity(bundle,changes,afterWbs=''){
 const name=String(changes.name||'').trim();if(!name||name.length>300)throw new Error('Informe um nome com até 300 caracteres.');const start=validDate(changes.start),finish=validDate(changes.finish);if(finish<start)throw new Error('O término não pode ser anterior ao início.');const predecessor=changes.predecessor||'',pred=bundle.wbs_rows.find(r=>r.wbs===predecessor);if(predecessor&&!pred)throw new Error('Predecessora não encontrada.');if(pred?.finish&&start<=pred.finish.slice(0,10))throw new Error('A atividade deve começar após a predecessora.');
 const wbs='MANUAL-'+crypto.randomUUID(),workdays=bundle.sequence?.settings?.workdays??true,row={wbs,name,start,finish,predecessor,summary:false,milestone:false,direct_elements:0,linked_elements:0,measured_elements:0,measurement_coverage_percent:null,phases:[changes.phase||'Atividades manuais'],quantities:[],planned_percent:null,actual_percent:null,reported_percent:null,delta_percent:null,weight:null,duration_days:duration(start,finish,workdays),evidence:'INFORMADO',rule:'Atividade adicionada pelo usuário; sem vínculo IFC automático'};
 const rows=[...bundle.wbs_rows],index=rows.findIndex(r=>r.wbs===afterWbs);rows.splice(index<0?rows.length:index+1,0,row);validateGraph(rows);return refresh(bundle,rows,bundle.elements,{action:'add',wbs,name});
}
export function removeActivity(bundle,wbs){const row=bundle.wbs_rows.find(r=>r.wbs===wbs);if(!row||row.summary)throw new Error('Remova uma atividade individual, não um grupo de resumo.');const rows=bundle.wbs_rows.filter(r=>r.wbs!==wbs).map(r=>r.predecessor===wbs?{...r,predecessor:row.predecessor||'',evidence:'INFORMADO'}:r),removed=bundle.elements.filter(e=>e.wbs===wbs),links=bundle.elements.filter(e=>e.wbs!==wbs);validateGraph(rows);return refresh(bundle,rows,links,{action:'remove',wbs,previous:row,removed_links:removed});}
