"use client";
import {useEffect,useRef,useState} from "react";
type Project={id:string;name:string;file_count?:number};
type ModelFile={id:string;name:string;size_bytes:number;status:string;created_at:string};
type Federation={id:string;name:string;file_count:number;project_id?:string};
async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await r.json() as {error?:string;projects:Project[];project:Project;files:ModelFile[];federations:Federation[];federation:Federation;uploadUrl:string};if(!r.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data;}
const mb=(bytes:number)=>(bytes/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})+" MB";
export default function Projects(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[projectName,setProjectName]=useState(""),[files,setFiles]=useState<ModelFile[]>([]),[federations,setFederations]=useState<Federation[]>([]),[selected,setSelected]=useState<string[]>([]),[federationName,setFederationName]=useState(""),[active,setActive]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[progress,setProgress]=useState(0),[uploadLabel,setUploadLabel]=useState("");
 const picker=useRef<HTMLInputElement>(null),generation=useRef(0);
 useEffect(()=>{let alive=true;api('/api/models/projects').then(d=>{if(!alive)return;setProjects(d.projects);const q=new URLSearchParams(window.location.search),id=q.get('project');setProjectId(d.projects.some((p:Project)=>p.id===id)?(id||''):d.projects[0]?.id||'');setActive(q.get('federation')||'');}).catch(e=>{if(alive)setNotice(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 async function refresh(id=projectId){const gen=++generation.current;const [a,b]=await Promise.all([api('/api/models/files?projectId='+encodeURIComponent(id)),api('/api/models/federations?projectId='+encodeURIComponent(id))]);if(gen!==generation.current)return;setFiles(a.files);setFederations(b.federations);}
 useEffect(()=>{setFiles([]);setFederations([]);setSelected([]);setFederationName('');if(projectId){void refresh(projectId).catch(e=>setNotice(e.message));}return()=>{generation.current++;};},[projectId]);
 useEffect(()=>{let alive=true;if(active&&projectId)api('/api/models/federations/'+active).then(d=>{if(alive&&d.federation.project_id===projectId){setSelected(d.files.map(f=>f.id));setFederationName(d.federation.name);}}).catch(e=>{if(alive)setNotice(e.message);});return()=>{alive=false;};},[active,projectId]);
 async function createProject(){setBusy(true);setNotice('');try{const d=await api('/api/models/projects',{name:projectName});setProjects(p=>[d.project,...p]);setProjectId(d.project.id);setProjectName('');setActive('');setNotice('Projeto criado. Agora envie seus IFCs.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 function sendFile(url:string,file:File){return new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onerror=()=>reject(new Error('Envio interrompido. Verifique sua conexão e tente novamente.'));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve();else{let message='Falha ao armazenar o IFC.';try{message=JSON.parse(xhr.responseText).error||message;}catch{}reject(new Error(message));}};xhr.send(file);});}
 async function upload(list:FileList|null){if(!list?.length||!projectId)return;const incoming=Array.from(list);if(incoming.some(f=>!f.name.toLowerCase().endsWith('.ifc')||f.size<1||f.size>100_000_000)){setNotice('Selecione arquivos IFC de até 100 MB cada.');if(picker.current)picker.current.value='';return;}setBusy(true);let completed=0;try{for(const file of incoming){setProgress(0);setUploadLabel(`Enviando ${completed+1} de ${incoming.length}: ${file.name}`);const d=await api('/api/models/files',{projectId,name:file.name,size:file.size});await sendFile(d.uploadUrl,file);completed++;}setNotice(`${completed} IFC${completed>1?'s':''} armazenado${completed>1?'s':''} na nuvem.`);}catch(e){setNotice(`${completed} arquivo(s) enviado(s). ${(e as Error).message} Os envios concluídos foram mantidos.`);}finally{setBusy(false);setUploadLabel('');if(picker.current)picker.current.value='';await refresh().catch(e=>setNotice(e.message));}}
 async function deleteFile(file:ModelFile){
  if(busy||!window.confirm(`Excluir “${file.name}” da biblioteca?\n\nO arquivo será apagado da nuvem e retirado das composições federadas. O histórico do cronograma e das medições será mantido. Esta ação não pode ser desfeita.`))return;
  setBusy(true);setNotice('');
  try{const r=await fetch('/api/models/files/'+encodeURIComponent(file.id),{method:'DELETE'});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível excluir o IFC.');
   setSelected(s=>s.filter(id=>id!==file.id));setActive('');window.history.replaceState(null,'',`/projetos?project=${encodeURIComponent(projectId)}`);
   await refresh();setNotice('IFC excluído da biblioteca e retirado das composições. O histórico do planejamento foi mantido.');
  }catch(e){setNotice((e as Error).message);}finally{setBusy(false);}
 }
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<20?[...s,id]:s);}
 async function openSaved(id:string){try{const d=await api('/api/models/federations/'+id);setSelected(d.files.map((f:ModelFile)=>f.id));setFederationName(d.federation.name);setActive(id);window.history.replaceState(null,'',`/projetos?project=${encodeURIComponent(projectId)}&federation=${encodeURIComponent(id)}`);}catch(e){setNotice((e as Error).message);}}
 async function saveFederation(){setBusy(true);try{const d=await api('/api/models/federations',{projectId,name:federationName.trim()||`Modelo federado · ${selected.length} IFC${selected.length>1?'s':''}`,fileIds:selected});await refresh();await openSaved(d.federation.id);setNotice('Composição salva. Você poderá reabri-la nesta biblioteca.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function useInPlanning(){if(!active)return;setBusy(true);try{await api('/api/models/active',{id:active});window.location.href='/planejamento?federation='+encodeURIComponent(active);}catch(e){setNotice((e as Error).message);setBusy(false);}}
 const total=files.filter(f=>selected.includes(f.id)).reduce((s,f)=>s+f.size_bytes,0);
 return <div className="app-shell library-shell"><aside className="sidebar"><a className="side-brand" href="/"><img src="/v2m-brand.svg" alt="V2M ENGENHARIA"/></a><div className="project-card"><b>Biblioteca de projetos</b><small>IFCs na nuvem</small></div><nav><a href="/">Visão geral</a><a className="active" href="/projetos">Projetos e modelos</a><a href="/planejamento">Planejamento</a><a href="/compras">Compras e custos</a><a href="/qualidade">Qualidade</a><a href="/diario">Diário de obra</a></nav><div className="side-foot">V2M ENGENHARIA<small>Projetos · Modelos · Federação</small></div></aside><main>
 <header className="command-bar"><b>V2M ENGENHARIA</b><a className="v2m-button" href="/">Visão geral</a></header><section className="page-title"><div><p>PROJETOS</p><h1>Biblioteca de modelos</h1><small>Envie os IFCs do projeto e abra até 20 arquivos juntos.</small></div></section>
 {notice&&<p className="library-notice" role="status">{notice}{notice.includes('Entre na sua conta')&&<> <a href="/signin-with-chatgpt?return_to=%2Fprojetos" target="_top">Entrar na conta</a></>}</p>}
 <section className="panel library-projects"><div><label htmlFor="library-project">Projeto</label><select id="library-project" value={projectId} disabled={busy||loading} onChange={e=>{setActive('');setProjectId(e.target.value);window.history.replaceState(null,'','/projetos');}}><option value="">{loading?'Carregando projetos…':'Selecione um projeto'}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><form onSubmit={e=>{e.preventDefault();void createProject();}}><label htmlFor="new-project">Novo projeto</label><div className="library-inline"><input id="new-project" value={projectName} maxLength={120} disabled={busy} placeholder="Nome da obra ou projeto" onChange={e=>setProjectName(e.target.value)}/><button className="v2m-button" disabled={busy||!projectName.trim()}>Criar projeto</button></div></form></section>
 {!projectId&&!loading&&<section className="panel library-empty"><h2>Crie seu primeiro projeto</h2><p>Os arquivos e as composições ficam salvos na sua biblioteca, para reabrir em outras sessões.</p></section>}
 {projectId&&<><div className="library-columns"><section className="panel"><div className="panel-title"><h2>Arquivos IFC</h2><button className="v2m-button" disabled={busy} onClick={()=>picker.current?.click()}>Enviar IFCs</button><input ref={picker} type="file" accept=".ifc" multiple hidden onChange={e=>void upload(e.target.files)}/></div><p className="library-help">Até 100 MB por arquivo. Enviar armazena o IFC na nuvem privada; abrir um arquivo local no visualizador antigo continua sendo uma operação local.</p>
 {busy&&uploadLabel&&<div role="status" className="library-progress"><b>{uploadLabel}</b><progress max={100} value={progress}/><span>{progress===100?'Confirmando armazenamento…':progress+'% enviado'}</span></div>}
 {!files.length&&<p className="library-empty">Nenhum IFC neste projeto. Use “Enviar IFCs” para começar.</p>}<div className="library-file-list">{files.map(f=><label className={'library-file '+(selected.includes(f.id)?'chosen':'')} key={f.id}><input type="checkbox" aria-label={'Selecionar '+f.name} checked={selected.includes(f.id)} disabled={busy||f.status!=='ready'||(!selected.includes(f.id)&&selected.length>=20)} onChange={()=>toggle(f.id)}/><span><b>{f.name}</b><small>{mb(f.size_bytes)} · {f.status==='ready'?'Disponível':f.status==='failed'?'Envio não concluído — envie novamente':f.status==='deleting'?'Exclusão interrompida — tente excluir novamente':'Envio pendente'}</small></span>{f.status==='ready'&&<a href={'/api/models/files/'+f.id} onClick={e=>e.stopPropagation()}>Baixar</a>}<button type="button" className="library-delete" disabled={busy||f.status==='uploading'} aria-label={'Excluir '+f.name} onClick={e=>{e.preventDefault();e.stopPropagation();void deleteFile(f);}}>Excluir</button></label>)}</div></section>
 <section className="panel"><div className="panel-title"><h2>Composição federada</h2><span>{selected.length} / 20 IFCs</span></div><label htmlFor="federation-name">Nome da composição</label><input id="federation-name" value={federationName} maxLength={120} placeholder="Estrutura + arquitetura + instalações" disabled={busy} onChange={e=>setFederationName(e.target.value)}/><p>{selected.length} selecionado(s) · {mb(total)}</p>{total>250_000_000&&<p className="library-help">Conjunto grande: a abertura depende da memória e da complexidade da geometria. Se o navegador ficar lento, abra menos IFCs.</p>}<button className="v2m-button" disabled={busy||!selected.length} onClick={()=>void saveFederation()}>Salvar e abrir juntos</button><p className="library-help">Os arquivos mantêm suas coordenadas. Exporte as disciplinas com a mesma origem e referência de projeto.</p><h3>Composições salvas</h3>{!federations.length?<p>Nenhuma composição salva.</p>:<div className="library-saved">{federations.map(f=><button key={f.id} disabled={busy||!f.file_count} className={active===f.id?'chosen':''} onClick={()=>void openSaved(f.id)}><b>{f.name}</b><span>{f.file_count} IFC(s) · {f.file_count?'Abrir':'Sem arquivos — crie uma nova composição'}</span></button>)}</div>}</section></div>
 <section className="panel library-viewer"><div className="panel-title"><h2>Visualização federada</h2><span>{active?'COMPOSIÇÃO SALVA':'SELECIONE OS IFCs'}</span>{active&&<button className="v2m-button" disabled={busy} onClick={()=>void useInPlanning()}>Usar no Planejamento</button>}</div>{active?<iframe title="Modelo IFC federado V2M" src={'/bim-viewer/federated.html?federation='+encodeURIComponent(active)}/>:<div className="library-empty"><h3>Abra as disciplinas no mesmo ambiente</h3><p>Selecione os IFCs na lista e clique em “Salvar e abrir juntos”. Você poderá ocultar cada disciplina e inspecionar seus elementos.</p></div>}</section></>}
 </main></div>;
}
